const NODES_PER_CLUSTER = 2;

const k = 20;

const NUMBER_OF_CLUSTERS = 5;
const TX_PER_BLOCK = 20;

const CLUSTER_SIZE = 20;

//const NUMBER_OF_NODES = ((NUMBER_OF_CLUSTERS-1) * NUMBER_OF_CLUSTERS) + 1;
const NUMBER_OF_NODES = NUMBER_OF_CLUSTERS*NODES_PER_CLUSTER;

const MIN_APPROVALS = Math.floor(2 * (NUMBER_OF_NODES / 3) + 1); 
const TRANSACTION_THRESHOLD = 10;

module.exports = {
	TRANSACTION_THRESHOLD,
	NUMBER_OF_NODES,
	MIN_APPROVALS,
	NUMBER_OF_CLUSTERS,
	NODES_PER_CLUSTER,
	CLUSTER_SIZE,
	k
}
